import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { PokemonIndex, usePokemon } from "../components/fetch";

const Home: NextPage = () => {
  const { pokemons, isLoading, isError } = usePokemon<PokemonIndex[]>(
    "https://raw.githubusercontent.com/jherr/pokemon/main/index.json"
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon list</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {isLoading && <p>Loading...</p>}

      <div className={styles.grid}>
        {pokemons
          ? pokemons.slice(0, 10).map((pokemon) => (
              <div className={styles.card} key={pokemon.id}>
                <Link href={`/pokemon/${pokemon.id}`}>
                  <a>
                    <Image
                      src={`https://raw.githubusercontent.com/jherr/pokemon/main/${pokemon.image}`}
                      layout="responsive"
                      alt={pokemon.name}
                      width={300}
                      height={200}
                      priority
                    />
                    <p className={styles.name}>{pokemon.name}</p>
                  </a>
                </Link>
              </div>
            ))
          : null}
      </div>
    </div>
  );
};

export default Home;
